### ISSUE TITLE
autoIncrement not working?

### ISSUE THREAD

**Issue by pwFoo** [leegeunhyeok/bxd#6]
Hi,
I played with autoIncrement value, but not sure if it not works how I expected.

Is autoIncrement key(Path) part of the data object?
For example if "id" is the keyPath autoIncrement I would like to omit "id" from my object I'll store to indexeddb?

example 
```
User.add({ name: "User1", age: 105 }) // should be saved as { id: <autoIncrement>, name: "User1", age: 105 }
```
Is that possible with bxd / indexeddb?

**Comment by leegeunhyeok** [comment]
@pwFoo Sorry for the late response.

`autoIncrement` option in IndexedDB behaves differently than other databases.

**in-line key**

```js
const User = database.create('user', {
  _id: {
    type: BoxDB.Types.NUMBER,
    key: true, // inline-key
  },
  name: BoxDB.Types.STRING,
  created_at: BoxDB.Types.DATE,
}, { autoIncrement: true }); // if enable autoIncrement, it will be ignored.
```

<img width="795" alt="image" src="https://github.com/leegeunhyeok/bxd/assets/26512984/13311430-d9c9-43a9-8880-d909a273fd8c">

- Indexed by `keyPath`. (in bxd, field's `key` option)
- It's always field in the data.

---

**out-of-line key**

```js
const User = database.create('user', {
  _id: type: BoxDB.Types.NUMBER,
  name: BoxDB.Types.STRING,
  created_at: BoxDB.Types.DATE,
}, { autoIncrement: true }); // out-of-line key
```

<img width="792" alt="image" src="https://github.com/leegeunhyeok/bxd/assets/26512984/45fa27df-b3f3-4f29-b031-4510d1b176d5">

- Indexed by `autoIncrement` option.
- It can not be data's field. (A virtual key is generated internally)
- out-of-line key can be used with `get`, `put`, `delete` methods.

## Answer

> Is autoIncrement key(Path) part of the data object?

No, autoIncrement key is virtual key.

> Is that possible with bxd / indexeddb?

No, it's not possible. you should manage the auto-increment key yourself.
or access to transaction of object store's `autoIncrement` property directly, you can get current auto increment value.

```js
// Sadly, bxd isn't supports to access transaction directly yet.
const objectStore = tx.objectStore('objectStoreName');

objectStore.autoIncrement; // number
```

**Comment by pwFoo** [comment]
Hi @leegeunhyeok,

thanks for answering my questions.
